### ISSUE TITLE
Possibility to disable template caching

### ISSUE THREAD

**Issue by Bombo** [ifandelse/Knockout.js-External-Template-Engine#10]
Hi,

first of all thanks for the great work porting the external template engine to Knockout 2.0! Looks really good and works very smoothly!

This is more of a question or feature request, than an issue: In the former version, it was possible to pass additional ajax options to the engine, e.g. to disable browser caching for the request. Is there an option in the new version or via the new infuser plugin?

Thanks,
Boris

**Comment by ifandelse** [comment]
My apologies for the delay in answering you!  It's been a busy month with holidays/travel and a new job, etc.  The answer is, yes, you can pass in any additional options, and you have two ways to do it:
- `infuser.defaults` (infuser provides a number of defaults already, but basically anything $.ajax handles should be usable, so you could simply say `infuser.defaults.cache = false`.
- in-line in the binding: `<div data-bind="template: { name: 'stats', templateUrl: 'templates/info', ajax: { cache: false } }"></div>`

Notice in the second item above I not only provided an ajax option, but also overrode the templateUrl where infuser will look to find the "stats.html" template.  Hope that helps!

**Comment by ifandelse** [comment]
Hopefully you caught that I updated my code sample above (second example of in-line binding usage).  You have to specify ajax options via `ajax: { /* ajax options here */ }`.
