### ISSUE TITLE
afterRender fires twice

### ISSUE THREAD

**Issue by grofit** [ifandelse/Knockout.js-External-Template-Engine#11]
I have a problem in the latest version where the afterRender fires twice due to its Async loading, once seems to be from the loading of the placeholder, then once for the loaded template.

I am not sure if this is something that can be fixed, but it is an issue that drove me mad, currently I have hacked it to load synchronously on my local version, but is there any way an option could be added to call getSync instead of get dependant on the variable...

infuser.config.async = false;

Here is a stackoverflow post with an example project link showing the problem:
http://stackoverflow.com/questions/8773824/knockoutjs-afterrender-issue-in-version-2-not-apparent-in-version-1-2-x/8794869#8794869

**Comment by ifandelse** [comment]
Hi there, I've created a repo with a modified version of the sample project you linked to from stackoverflow: https://github.com/ifandelse/Knockout.js-External-Templates---afterRender-Solution.

I'm able to access the template binding context and wrap the afterRender inside another function that checked the template source's "loaded" boolean flag, and prevent afterRender from firing until loaded = true.  I'm going to go ahead and commit this change to the master branch of the External Template Engine repo, but I'm also going to ping @RyanNeimeyer about it to get his weigh-in.

**Comment by rniemeyer** [comment]
@ifandelse This is exactly how I would have thought to handle this situation.  Only two minor changes, that I would make:

1- Currently, when KO executes the `afterRender` function `this` is set to the options object.  Is that useful?  Probably not that often, but it would be good for you to match that functionality.  When you execute the function the way that you are now, `this` will be the window object.  

2- The `afterRender` function is passed an array of nodes in the first argument, and the view model (current data being bound at that scope) as the second argument.  I would think that you would want to make sure that your wrapper passed those as well.

To match KO exactly, I would do:

```
    if(options.afterRender) {
        origAfterRender = options.afterRender;
        options.afterRender = function() {
            if(self.loaded) {
                origAfterRender.apply(options, arguments);
            }
        }
    }
```

**Comment by ifandelse** [comment]
Funny - you read my mind!  I wondered about the context and args for afterRender, and almost asked specifically about it.  I didn't see arguments being passed into the afterRender in the sample project, which I thought was odd.  Either way -I'll have the change applied and pushed in a few min.  Thanks!

**Comment by rniemeyer** [comment]
Nice!

**Comment by jasonkenneth** [comment]
@ifandelse This appears to be happening again. We're using knockout-2.1.0 and the latest of the externalTemplates plugin (Version 2.0.4) grabbed from nuget. Our setup is kind of complicated but I will try to repro with a jsfiddle sample if you need me to. I am stepping through the code, and I see where the original afterRender is being wrapped during the creation of ExternalTemplateSource. However, that afterRender is never getting called. My browser is Chrome 20.0.1132.57 m. Disabling the feature via infuser.defaults.useLoadingTemplate causes no html to be rendered, but afterRender is still getting called twice (albeit I can do a more simple test for nodes.length==0 in my afterRender handler).

**Comment by hollis21** [comment]
@jasonkenneth  I found the cause of that and you can find the fix here (https://github.com/fazzamar/Knockout.js-External-Template-Engine/commit/5b053acd0465cd5c98b947d97cbd4d2e675c9f52) I haven't tested it extensively, but it does seem to fix the issue.
