### ISSUE TITLE
Issue since updating to latest version

### ISSUE THREAD

**Issue by grofit** [ifandelse/Knockout.js-External-Template-Engine#12]
Just updated to the latest version for the fix with double afterRenders however now I get an error:

koExternalTemplateEngine_all.js - line 243

if(options.afterRender) {

I keep getting options is undefined, however self.options is populated however there is no afterRender.

**Comment by ifandelse** [comment]
This should teach me to not code at 2 AM.  I've updated the source to check self.options (instead of options).  Let me know if that takes care of things for you.

**Comment by ifandelse** [comment]
Let me know if this worked out for you - I'll keep the issue open for a bit in case...

**Comment by grofit** [comment]
Seemed to fix the issue, sorry forgot to update.

**Comment by ifandelse** [comment]
No prob - just making sure things were good on your end.  Thanks!
