### ISSUE TITLE
Unable to override templateUrl in data-bind

### ISSUE THREAD

**Issue by genereddick** [ifandelse/Knockout.js-External-Template-Engine#16]
While I can set a default templateUrl which is correctly picked up:

```
infuser.defaults.templateUrl = "/templates";
```

The following data-bind call loads the foo file from the '/templates' folder and binds it:

```
 <div data-bind="template: { name: 'foo', data: $data }">
```

However, if I attempt to override the templateUrl in the data-bind attribute, calling the same file but now from a subfolder '/templates/subfolder' it is ignored and attempts to load the file from the default folder. Removing the default setting causes it to look for the file in the root of the directory:

```
<div data-bind="template: { name: 'foo', templateUrl: '/templates/subfolder,  data: $data }">
```

**Comment by ifandelse** [comment]
Hi @genereddick - are you using jQuery templates or native templates?  Unfortunately, template url overrides aren't possible with jQuery templates, as the KO internals don't expose what I need to make it possible.  Only native templates can have that information overridden in the template binding...

**Comment by genereddick** [comment]
I'm using native templates (unless I misunderstand the definition — the code is not wrapped in a script tag). Here is a slightly fuller example. With the code below, my expectation is that it would load the copy of foo in the subfolder and bind it to the value of subfolderMessage: I'm in the subfolder, but I get the default file / message: I'm in default folder

the index file: 

```
<div id="wrapper">
    <div data-bind="template: { name: 'foo', templateUrl: '/templates/subfolder'}">
    </div>
</div>
```

In a script block:    

```
    $(function () {
        infuser.defaults.templateSuffix = ".tmpl.html";
        infuser.defaults.templateUrl = "/templates";
        var vm = {
            defaultMessage: ko.observable("I'm in default folder"),
            subfolderMessage: ko.observable("I'm in the subfolder")
        };
        ko.applyBindings(vm, document.getElementById("wrapper"));
    });
```

And the template files:

```
/templates/foo.tmpl.html:
<p data-bind="text: defaultMessage"></p>

/templates/subfolder/foo.tmpl/html:
<p data-bind="text: subfolderMessage"></p>
```

**Comment by ifandelse** [comment]
@genereddick - sorry if my question wasn't clear.  I'm actually asking what template syntax you are using?  Any chance you could paste in the html code from one of your templates?  (Note that you might have to surround it by tick marks `so that it will look similar to this`.  Also - just to verify, is your "templates" folder at the root of your site?  If not, you'll need to remove the leading "/" so that the path will be treated as relative

**Comment by genereddick** [comment]
I had assumed that because I wasn't surrounding the template code with a script block that I was using the Knockout native binding. However, I was referencing the jquery.tmpl js file and, presumably,  its presence was sufficient to make it the default template syntax?

I removed the jquery.tmpl reference and it is working as expected. I've only been using this for a week and I can't imagine living without it. Thanks for the help!

**Comment by ifandelse** [comment]
You are correct - including jquery.tmpl auto configures the template engine I wrote to expect jQuery templates.  Glad you got it figured out!  Happy coding! :-)
