### ISSUE TITLE
Templating fails in IE7

### ISSUE THREAD

**Issue by MrClyfar** [ifandelse/Knockout.js-External-Template-Engine#18]
Hi there.

I viewed a Knockoutjs website, which uses the External Templates plugin, in IE7 and got this error:

"SCRIPT5009: 'JSON' is undefined"

Is there room for External Templates to support IE7?

Thanks.
Jas.

**Comment by ifandelse** [comment]
IE7 doesn't have JSON support natively, unfortunately.  However, you can include json2.js (go here: https://github.com/douglascrockford/JSON-js/) - be sure to include it before any of the KO assets, etc.  The json2.js file will add a global JSON object, etc.  Let me know if you still have issues....

**Comment by MrClyfar** [comment]
Hi Jim.
Thank you for your reply. I will look into using json2.js now, really appreciate that info.
Cheers.Jas.
