### ISSUE TITLE
Feature Request: Pass HTTP parameters to template

### ISSUE THREAD

**Issue by thelinuxlich** [ifandelse/Knockout.js-External-Template-Engine#2]
It would be nice if this plugin recognizes querystring like "?foo=bar" as parameters passed for the template.

**Comment by ifandelse** [comment]
Can you give me a bit more insight as to what you are looking for as well as some explanation why you want to take this approach (versus, say, an approach where you have a helper function passed in as the template name, which parses the query string for foo=bar)?  Are you looking to use the query string to dynamically select a template name, or are you looking to pass other params to the template?  Thanks!

**Comment by thelinuxlich** [comment]
Yeah, I would like to pass other params to the template, see this code:

https://github.com/thelinuxlich/knockout.spi/blob/master/js/main.js

There is a templateParams object, which receives these GET params, I don't know if this would fit into your plugin

**Comment by ifandelse** [comment]
Thanks for the code example - I will look at this and get back to you.

**Comment by ifandelse** [comment]
I'm sorry that I have left this hanging here so long!  With the new templating in 1.3, is this still something you need?

**Comment by thelinuxlich** [comment]
I've seen the latest update and it looks great, I need to update my SPI example to see if this feature is still needed. I think you can close it, since we can pass a data object containing params to the external template right?

**Comment by ifandelse** [comment]
Yes - templateOptions work fine on the external templates.  I've included a small (& contrived) example of it working in the examples folder in the repo now.  Thanks!
