### ISSUE TITLE
useLoadingTemplate = false Prevents Template Rendering

### ISSUE THREAD

**Issue by nkoterba** [ifandelse/Knockout.js-External-Template-Engine#20]
I'm trying to not show anything on the webpage while my templates are loading.  The default behavior is to show a div with 'Loading...'

Perhaps I'm using the Template Engine plugin incorrectly, but when I set useLoadingTemplate to false:

``` javascript
infuser.defaults.useLoadingTemplate = false;
```

my templates never render.  

As a workaround, if I change the loadingTemplate to be an empty div, I get the desired affect:

``` javascript
infuser.defaults.loadingTemplate.content = '<div/>'
```

Am I using useLoadingTemplate incorrectly?

The user sees no loading template and my template does render.

**Comment by DaveVdE** [comment]
I'm having the same problem. This should really be looked at. My hunch is that it works as advertized in Infuser, but it breaks the external template engine.

**Comment by ifandelse** [comment]
My apologies - this project has been retired. I wish had the bandwidth to keep up, but alas, I do not. You can read more [here](http://ifandelse.com/know-when-to-walk-away/). I'm open to transferring it to anyone that really wants it.
