### ISSUE TITLE
SVG elements

### ISSUE THREAD

**Issue by gilesbradshaw** [ifandelse/Knockout.js-External-Template-Engine#22]
I did an observable template engine based on this.  I am using it to template SVG elements - so I hold the templates in my view model and bind to them and the resulting template also binds to other parts of my view model.  This way you can change the template on the fly from the vie model.

you might want to look at what I did as you could add this SVG option to your code too:

https://github.com/GilesBradshaw/Knockout.js-Observable-Template-Engine

```
       if (!options.svg)
            return engine.renderTemplateSource(templateSource, bindingContext, options);
        else {
            var doc = new window.DOMParser().parseFromString(
               '<svg xmlns="http://www.w3.org/2000/svg">' + templateSource.text() + '</svg>',
               'application/xml');
            doc = document.importNode(doc.documentElement, true);
            var ret = [];
            var child = doc.firstChild;
            while (child) {
                ret.push(child);

                child = child.nextSibling;
            }
            return ret;
        }
```

**Comment by ifandelse** [comment]
thanks for the info @gilesbradshaw. I've actually retired this project as I don't have time to keep up with it amongst everything else. Glad to see others like yourself continuing to innovate for KO. :smile:
