### ISSUE TITLE
AJAX results empty check when trying to load external template files

### ISSUE THREAD

**Issue by onlyurei** [ifandelse/Knockout.js-External-Template-Engine#25]
When the content of the AJAX requests to load the external templates is empty, the engine should throw a helpful exception that shows up in the console to help developers debug. I see the engine already has an AJAX error handler templateGetError, but it's based on the HTTP status code. There should be an empty check inside templateGetSuccess to make sure response has content.

Just spent a couple hours try to figure out why the ko bindings don't work in IE 9 and below in some environments only, but work in other environments.

After some deep stack trace, it leads to the this server-specific issue:
http://stackoverflow.com/questions/10194257/could-not-complete-the-operation-due-to-error-c00ce56e

If the external template had this error info, it would be much easier to troubleshoot the problem.

**Comment by ifandelse** [comment]
My apologies - this project has been retired. I wish had the bandwidth to keep up, but alas, I do not. You can read more [here](http://ifandelse.com/know-when-to-walk-away/). I'm open to transferring it to anyone that really wants it.
