### ISSUE TITLE
external template with KO 2.2.1 and jQuery 1.8

### ISSUE THREAD

**Issue by bgnadav** [ifandelse/Knockout.js-External-Template-Engine#26]
KO 2.2.1 use jQuery 1.8 parseHTML option (if jquery 1.8 is loaded..), but the result is null and not an empty array, the null is passed on, and the template is not rendered.

**Comment by ifandelse** [comment]
My apologies - this project has been retired. I wish had the bandwidth to keep up, but alas, I do not. You can read more [here](http://ifandelse.com/know-when-to-walk-away/). I'm open to transferring it to anyone that really wants it.
