### ISSUE TITLE
No info about license

### ISSUE THREAD

**Issue by mbukowicz** [ifandelse/Knockout.js-External-Template-Engine#30]
This library is useless (from my perspective), as there is no information about under which license it is distributed. Please, choose a license and make this information visually distinguished.

**Comment by ifandelse** [comment]
My apologies - this project has been retired. I wish had the bandwidth to keep up, but alas, I do not. You can read more [here](http://ifandelse.com/know-when-to-walk-away/). I'm open to transferring it to anyone that really wants it.

BTW - it's MIT. I will add a license file when I update the readme with the project status.
