### ISSUE TITLE
is it possible to override a template ?

### ISSUE THREAD

**Issue by MarcoVecchi** [ifandelse/Knockout.js-External-Template-Engine#31]
Hi, i'm using this great plugin to load .html templates.
i some cases i need to inject additional html inside the template, how can i do that ?
i have seen i could override the infuser preRender option, but it's not used with infuser.get that (as fa well as i understand) provides the template to the knokocut engine.

Thx Marco

**Comment by ifandelse** [comment]
My apologies - this project has been retired. I wish had the bandwidth to keep up, but alas, I do not. You can read more [here](http://ifandelse.com/know-when-to-walk-away/). I'm open to transferring it to anyone that really wants it.
