### ISSUE TITLE
Best way to inline templates while build process

### ISSUE THREAD

**Issue by petrovskyy** [ifandelse/Knockout.js-External-Template-Engine#33]
Hi!
Our build process relies on r.js & grunt tasks. Goal is to combine js,css and templates.
But can't find any out of the box solution for templates. Before we start reinventing the wheel could anybody please share any ideas about this.
Thanks in advance

**Comment by ifandelse** [comment]
My apologies - this project has been retired. I wish had the bandwidth to keep up, but alas, I do not. You can read more [here](http://ifandelse.com/know-when-to-walk-away/). I'm open to transferring it to anyone that really wants it.
