### ISSUE TITLE
How to know when template loading is "done done".

### ISSUE THREAD

**Issue by DaveVdE** [ifandelse/Knockout.js-External-Template-Engine#34]
We're using the external tempalte engine quite extensively. We have templates that themselves contain template bindings. This works pretty well, but a recurring problem is that `afterRender` doesn't quite do what we want.

When using a plugin like jQuery UI's carrousel, we need that `afterRender` binding to kick in when the template loading has done, and all nested loading and binding has also completed. 

We're currently experimenting with various tricks and workarounds, but that's what they really are: workarounds. We'd like to know your take on this.

**Comment by ifandelse** [comment]
My apologies - this project has been retired. I wish had the bandwidth to keep up, but alas, I do not. You can read more [here](http://ifandelse.com/know-when-to-walk-away/). I'm open to transferring it to anyone that really wants it.
