### ISSUE TITLE
When navigating away from a page while templates are still loading, errors are shown before the new page has started loading.

### ISSUE THREAD

**Issue by DaveVdE** [ifandelse/Knockout.js-External-Template-Engine#35]
This happens because the AJAX call is aborted (status code 0) but the engine does not test for this condition to avoid showing these 'errors'.

**Comment by ifandelse** [comment]
My apologies - this project has been retired. I wish had the bandwidth to keep up, but alas, I do not. You can read more [here](http://ifandelse.com/know-when-to-walk-away/). I'm open to transferring it to anyone that really wants it.
