### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. 

### ISSUE THREAD

**Issue by heenac** [ifandelse/Knockout.js-External-Template-Engine#36]

**Comment by ifandelse** [comment]
It sounds like you are trying to run the examples from the file system, rather than using a web server - is this the case? If so, please use IIS, node or any other web server to serve the files, since CORs via the file system isn't supported.

**Comment by heenac** [comment]
The purpose i need to run this website locally is  for burning it on a few dvd's and distributing it to a  set of people so that they can run the website on their local machines

Is it possible.

**Comment by ifandelse** [comment]
It's important to understand what's happening here. If you have a site served from "foo.com", and it makes requests (from within your JavaScript) to download resources from "bar.com" (a different domain), the **server** at "bar.com" needs to provide the `Access-Control-Allow-Origin` header, which would specify the domain(s) allowed to request the resource (or a `*` if it were allowing _any_ domain). Without this header, the browser client itself (Chrome, IE, FF, etc.) will throw the security exception you encountered (this is standard web security and is implemented at the browser level - it's not a problem with this library).  When you're using a web platform (whether it be IIS + ASP.Net, PHP, Ruby/Rails, Node.js, etc.), it's possible to customize how your server responds to requests and add the `Access-Control-Allow-Origin` header where necessary. However, you're serving files from the _file system_ (no web server is in play), thus you do not have a way to add the header.

So - the short answer to your question is "no". The long answer might _not_ be no if you can find any Chrome command line switch args that would enable Chrome to support what you're doing. See [this](http://stackoverflow.com/a/4752452/713567) for an example of what I'm referring to. Launching browsers with these kinds of custom args is not intended for production use, however.
